enum ErrorType {
    INTERNAL = 'INTERNAL',
    INVALID_REQUEST_PARAM = 'INVALID_REQUEST_PARAM',
    UNKNOWN = 'UNKNOWN',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
}

export default ErrorType